Implement #26
sksat/compose-cd pull request #27
Opened 2022-01-10 00:38 UTC by kory33

SSIA

2022-01-11 14:00 UTC, sksat requested changes

2022-01-11 14:00 UTC, sksat commented on compose-cd
> +	load_global_config
これ初回インストール時コケる

2022-01-11 14:14 UTC, sksat commented on compose-cd
> +	load_global_config
やるとしたら`/etc/compose-cd/config`があるか確認してあったらここらへんをスキップ & スキップするオプション追加，かなあ．

2022-01-12 05:16 UTC, kory33 commented on compose-cd
> +	load_global_config
問答無用でtouchしとくだとダメ？

2022-01-12 06:06 UTC, sksat commented on compose-cd
> +	load_global_config
これなに

2022-01-12 06:45 UTC, kory33 commented on compose-cd
> +	load_global_config
コケるってのはファイルが存在せずにコケるってことですよね
なんでloadする前にtouchしとけば別に良いんでないという気持ちです

2022-01-12 07:07 UTC, kory33 commented on compose-cd
> +	load_global_config
```suggestion
        touch /etc/compose-cd/config
	load_global_config
```

みたいなの想定してた

2022-01-12 07:15 UTC, sksat commented on compose-cd
> +	load_global_config
いや，`load_global_config`くんはファイル無かったらエラー吐くやつなんですよ．
それで今問題が起こることは無いけれど意図が変わってくるのでナシです．
https://github.com/sksat/compose-cd/blob/51b00b7103a67983833a076b2ea204bddd5f146b/compose-cd#L53-L56

2022-01-12 07:23 UTC, kory33 commented on compose-cd
> +	load_global_config
ん、なので `load_global_config` をするより前に `touch` すればいいんじゃないというsuggestionです　`install` 内ではどうせ直後に `tee` してるし

2022-01-12 07:36 UTC, sksat commented on compose-cd
> +	load_global_config
無のconfigを`load_global_config`するという状態が発生しうるのが嫌という話です

2022-01-12 07:38 UTC, kory33 commented on compose-cd
> +	load_global_config
これマジ？フ～ム

2022-01-12 07:42 UTC, sksat commented on compose-cd
> +	load_global_config
それで問題はないが僕が嫌という話です(touchではなく「問答無用で」の部分が嫌という話なのでどうしようもない)．そもそも雑に`source`しているのをどうにかしたい気持ちなどもあり，これで動くやんけで雑に`load_global_config`を呼ぶ場所を増やしたくない．

2022-01-12 07:47 UTC, sksat requested changes

2022-01-12 07:47 UTC, sksat commented on compose-cd
>  	mkdir /etc/compose-cd
再インストールのことを考えるやつなので
```suggestion
	mkdir -p /etc/compose-cd
```

2022-01-12 07:51 UTC, kory33 commented on compose-cd
>  	mkdir /etc/compose-cd
`/etc` 消えてることある？

2022-01-12 07:52 UTC, kory33 commented on compose-cd
>  	mkdir /etc/compose-cd
あ、 `no error if existing` の方の効能を期待しているのか、理解(なにがparentsだよという気持ちになってしまった)

2022-01-12 07:53 UTC, kory33 commented on compose-cd
> +	load_global_config
super config system雑すぎてこれ以上雑にしたくないというのはまぁN理ある

2022-01-12 07:53 UTC, sksat commented on compose-cd
>  	mkdir /etc/compose-cd
はい．そしてそちらの使われ方の方があまりに多い．

2022-01-12 07:58 UTC, kory33 commented on compose-cd
>  	mkdir /etc/compose-cd
これこのPRに含めますか？

2022-01-12 08:00 UTC, sksat commented on compose-cd
>  	mkdir /etc/compose-cd
`compose-cd install`での再インストールを考慮し始めるやつなので文脈同じだと思う(少なくとも僕からすると)

2022-01-12 08:03 UTC, sksat commented on compose-cd
> +	load_global_config
はい(はい)

2022-01-12 08:08 UTC, kory33 commented on compose-cd
>  	mkdir /etc/compose-cd
我々のuse-caseでは変数の入力の手間を減らすために一部設定を「決め打ちしておきたい」みたいな要求があり、その観点だと被ってる部分が無いわけではないが別文脈かなという感じ（これ元Issueにそう書いた方がいいな　説明不足でした）

2022-01-12 08:09 UTC, kory33 commented on compose-cd
>  	mkdir /etc/compose-cd
> 我々のuse-caseでは変数の入力の手間を減らすために一部設定を「決め打ちしておきたい」みたいな要求があり、その観点だと被ってる部分が無いわけではないが別文脈かなという感じ（これ元Issueにそう書いた方がいいな　説明不足でした）

https://github.com/GiganticMinecraft/seichi_infra/blob/d3ffdbfe96272d160ae8fbcfff4181b6a8e3efd8/seichi-onp-network-iap/setup-server.sh#L6-L9これです

2022-01-12 08:11 UTC, sksat commented on compose-cd
>  	mkdir /etc/compose-cd
文脈で言うとタイトルがFix/Implement #issueで本文がSSIAはパッと見た時に何も分からないのでどっちかになんか書いてくれの気持ちがあります．
あとタイトルにIssue number書かれても飛べないので本文に`Fix #hoge`とか書いてlinkしてもらう方が5億倍マシ．

2022-01-12 08:13 UTC, kory33 commented on compose-cd
>  	mkdir /etc/compose-cd
> 文脈で言うとタイトルがFix/Implement #issueで本文がSSIAはパッと見た時に何も分からないのでどっちかになんか書いてくれの気持ちがあります． あとタイトルにIssue number書かれても飛べないので本文に`Fix #hoge`とか書いてlinkしてもらう方が5億倍マシ．

OK

2022-01-12 08:19 UTC, kory33 commented
問題定義がｸﾞﾁｬｧとしてしまい大変申し訳ない気持ち　このPRは閉じとく

2022-01-12 08:19 UTC, closed without merging